### ISSUE TITLE
Not working for Oqtane

### ISSUE THREAD

**Issue by DiegelB** [2sic/landing-page-builder#22]
I am not sure if this module is working for Oqtane. I am running Oqtane 5.2.0 and the newest releases of 2sxc and the landing page builder (18.00.00 and 2.0.0 respectively). When I installed the module by downloading the .zip from github and adding the module to the page I am getting this error:

`Error: ToSic.Sxc.Razor.DotNetOverrides.CompilationFailedException: Resources.CompilationFailed l44nldol.d2u(25,96): error CS0234: The type or namespace name 'Dnn' does not exist in the namespace 'ToSic.Sxc' (are you missing an assembly reference?) l44nldol.d2u(42,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(43,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context l44nldol.d2u(44,13): error CS0103: The name 'WriteAttributeValue' does not exist in the current context l44nldol.d2u(45,13): error CS0103: The name 'WriteAttributeValue' does not exist in the current context l44nldol.d2u(53,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context l44nldol.d2u(54,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(62,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(70,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(78,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(86,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(94,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(102,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(110,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(111,13): error CS0103: The name 'BeginWriteAttribute' does not exist in the current context l44nldol.d2u(112,13): error CS0103: The name 'WriteAttributeValue' does not exist in the current context l44nldol.d2u(113,13): error CS0103: The name 'WriteAttributeValue' does not exist in the current context l44nldol.d2u(114,13): error CS0103: The name 'WriteAttributeValue' does not exist in the current context l44nldol.d2u(122,13): error CS0103: The name 'EndWriteAttribute' does not exist in the current context l44nldol.d2u(123,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(131,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(139,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(147,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(155,13): error CS0103: The name 'WriteLiteral' does not exist in the current context l44nldol.d2u(163,13): error CS0103: The name 'WriteLiteral' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(4,15): error CS0103: The name 'CreateInstance' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(5,23): error CS0103: The name 'CreateInstance' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(11,56): error CS0103: The name 'WriteAttributeValue' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(12,6): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(13,6): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(13,7): error CS0103: The name 'Edit' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(13,23): error CS0103: The name 'Header' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(15,6): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(16,35): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(16,36): error CS0103: The name 'Edit' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(17,10): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(17,11): error CS0103: The name 'RenderPage' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(19,31): error CS0103: The name 'AsList' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(19,38): error CS0103: The name 'Data' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(20,55): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(20,56): error CS0103: The name 'Edit' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(21,49): error CS0103: The name 'WriteAttributeValue' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(22,22): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(24,18): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(28,10): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(28,27): error CS0103: The name 'Header' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(32,2): error CS0103: The name 'Write' does not exist in the current context C:\inetpub\oqtane\2sxc\2\Landing Page Builder\live\Benefits\_Benefits - image left.cshtml🎯(32,3): error CS0103: The name 'RenderPage' does not exist in the current context at ToSic.Sxc.Razor.RazorCompiler.FindViewAsync(ActionContext actionContext, String partialName, IApp app, HotBuildSpec spec) at ToSic.Sxc.Razor.RazorCompiler.CompileView(String partialName, Action`1 configure, IApp app, HotBuildSpec spec) at ToSic.Sxc.Razor.RazorRenderer.RenderToStringAsync[TModel](String templatePath, TModel model, Action`1 configure, IApp app, HotBuildSpec hotBuildSpec) at ToSic.Sxc.Razor.RazorEngine.RenderTask(RenderSpecs specs)`

I've tried different templates and looked through the code. It seems to be using DNN rather than Oqtane. Maybe I downloaded the wrong version! Any help is appreciated. 

Thanks,
Ben

**Comment by iJungleboy** [comment]
This App is quite old and hasn't been updated for 2 years. 

So I believe it never underwent the Oqtane migration yet, so as of now, it's not Oqtane compatible. 

Anybody wanting to do it is free to do so, but we from 2sic probably won't have any capacity for this specific App (low priority) in 2024.

**Comment by DiegelB** [comment]
Thanks for the reply and all the work you all do!
